### ISSUE TITLE
Coding workflow

### ISSUE THREAD

**Issue by sergeyradkevich** [yuriidanyliak/TaDa#15]
- Learn the flow https://guides.github.com/introduction/flow/
- always see diffs before push(!)
- clearly understanding when to merge PRs yourself

**Comment by yuriidanyliak** [comment]
Got acquainted with the topics.

**Comment by yuriidanyliak** [comment]
@sergeyradkevich, would I close the issue or we will yet talk about the subject?

**Comment by sergeyradkevich** [comment]
@yuriidanyliak, we will discuss and then close the issue.
